language: c

env: 
  global:
    - INCLUDE=addons/sourcemod/scripting/include/
    - SCRIPTING=addons/sourcemod/scripting/
    - PLUGINS=addons/sourcemod/plugins/
    - HOME=ftp.toastdev.de/plugins
  matrix:
    - SOURCEMOD=1.9

before_install:
  - sudo apt-get update
  - sudo apt-get install gcc-multilib
  - sudo apt-get install lynx
  - sudo apt-get install lib32stdc++6
  - mkdir build-env

install:
    - SMPACKAGE="http://sourcemod.net/latest.php?os=linux&version=${SMVERSION}"
    - wget $SMPACKAGE
    - tar xfz $(basename $SMPACKAGE)
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - PATH+=":$PWD"
    - cd include

before_script:
  - chmod +rx build-env/addons/sourcemod/scripting/spcomp
  - chmod +rx build-env/addons/sourcemod/scripting/compile.sh
  - cd build-env/addons/sourcemod/scripting/
  
script:
  - ./compile.sh
  